language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.9"

notifications:
    email: false

install:
    - pip install numpy
    - pip install pytest
    - pip install matplotlib
    
script: 
    - pytest testGOL.py